# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/items.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/items.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/items.proto\x12\x08items.v1\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x11\x43reateItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\"9\n\x10ListItemsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"K\n\x11ListItemsResponse\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.items.v1.Item\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"A\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\")\n\x15SubscribeItemsRequest\x12\x10\n\x08item_ids\x18\x01 \x03(\t\"e\n\nItemUpdate\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05\x66ield\x18\x02 \x01(\t\x12\x11\n\told_value\x18\x03 \x01(\t\x12\x11\n\tnew_value\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\x8f\x02\n\x0cItemsService\x12\x33\n\x07GetItem\x12\x18.items.v1.GetItemRequest\x1a\x0e.items.v1.Item\x12\x39\n\nCreateItem\x12\x1b.items.v1.CreateItemRequest\x1a\x0e.items.v1.Item\x12\x44\n\tListItems\x12\x1a.items.v1.ListItemsRequest\x1a\x1b.items.v1.ListItemsResponse\x12I\n\x0eSubscribeItems\x12\x1f.items.v1.SubscribeItemsRequest\x1a\x14.items.v1.ItemUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.items_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETITEMREQUEST']._serialized_start=32
  _globals['_GETITEMREQUEST']._serialized_end=60
  _globals['_CREATEITEMREQUEST']._serialized_start=62
  _globals['_CREATEITEMREQUEST']._serialized_end=108
  _globals['_LISTITEMSREQUEST']._serialized_start=110
  _globals['_LISTITEMSREQUEST']._serialized_end=167
  _globals['_LISTITEMSRESPONSE']._serialized_start=169
  _globals['_LISTITEMSRESPONSE']._serialized_end=244
  _globals['_ITEM']._serialized_start=246
  _globals['_ITEM']._serialized_end=311
  _globals['_SUBSCRIBEITEMSREQUEST']._serialized_start=313
  _globals['_SUBSCRIBEITEMSREQUEST']._serialized_end=354
  _globals['_ITEMUPDATE']._serialized_start=356
  _globals['_ITEMUPDATE']._serialized_end=457
  _globals['_ITEMSSERVICE']._serialized_start=460
  _globals['_ITEMSSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
