# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import items_pb2 as protos_dot_items__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/items_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/items.v1.ItemsService/GetItem',
                request_serializer=protos_dot_items__pb2.GetItemRequest.SerializeToString,
                response_deserializer=protos_dot_items__pb2.Item.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/items.v1.ItemsService/CreateItem',
                request_serializer=protos_dot_items__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=protos_dot_items__pb2.Item.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_unary(
                '/items.v1.ItemsService/ListItems',
                request_serializer=protos_dot_items__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=protos_dot_items__pb2.ListItemsResponse.FromString,
                _registered_method=True)
        self.SubscribeItems = channel.unary_stream(
                '/items.v1.ItemsService/SubscribeItems',
                request_serializer=protos_dot_items__pb2.SubscribeItemsRequest.SerializeToString,
                response_deserializer=protos_dot_items__pb2.ItemUpdate.FromString,
                _registered_method=True)


class ItemsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItem(self, request, context):
        """Unary метод для получения одного предмета
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Unary метод для создания предмета
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Unary метод для списка предметов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeItems(self, request, context):
        """Streaming метод - подписка на обновления предметов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=protos_dot_items__pb2.GetItemRequest.FromString,
                    response_serializer=protos_dot_items__pb2.Item.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=protos_dot_items__pb2.CreateItemRequest.FromString,
                    response_serializer=protos_dot_items__pb2.Item.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=protos_dot_items__pb2.ListItemsRequest.FromString,
                    response_serializer=protos_dot_items__pb2.ListItemsResponse.SerializeToString,
            ),
            'SubscribeItems': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeItems,
                    request_deserializer=protos_dot_items__pb2.SubscribeItemsRequest.FromString,
                    response_serializer=protos_dot_items__pb2.ItemUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'items.v1.ItemsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('items.v1.ItemsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/items.v1.ItemsService/GetItem',
            protos_dot_items__pb2.GetItemRequest.SerializeToString,
            protos_dot_items__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/items.v1.ItemsService/CreateItem',
            protos_dot_items__pb2.CreateItemRequest.SerializeToString,
            protos_dot_items__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/items.v1.ItemsService/ListItems',
            protos_dot_items__pb2.ListItemsRequest.SerializeToString,
            protos_dot_items__pb2.ListItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/items.v1.ItemsService/SubscribeItems',
            protos_dot_items__pb2.SubscribeItemsRequest.SerializeToString,
            protos_dot_items__pb2.ItemUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
