# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTicket = channel.unary_unary(
                '/tickets.v1.TicketsService/GetTicket',
                request_serializer=service__pb2.GetTicketRequest.SerializeToString,
                response_deserializer=service__pb2.Ticket.FromString,
                _registered_method=True)
        self.CreateTicket = channel.unary_unary(
                '/tickets.v1.TicketsService/CreateTicket',
                request_serializer=service__pb2.CreateTicketRequest.SerializeToString,
                response_deserializer=service__pb2.Ticket.FromString,
                _registered_method=True)
        self.UpdateTicketStatus = channel.unary_unary(
                '/tickets.v1.TicketsService/UpdateTicketStatus',
                request_serializer=service__pb2.UpdateTicketStatusRequest.SerializeToString,
                response_deserializer=service__pb2.Ticket.FromString,
                _registered_method=True)
        self.ListTickets = channel.unary_unary(
                '/tickets.v1.TicketsService/ListTickets',
                request_serializer=service__pb2.ListTicketsRequest.SerializeToString,
                response_deserializer=service__pb2.ListTicketsResponse.FromString,
                _registered_method=True)


class TicketsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTicketStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicket,
                    request_deserializer=service__pb2.GetTicketRequest.FromString,
                    response_serializer=service__pb2.Ticket.SerializeToString,
            ),
            'CreateTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTicket,
                    request_deserializer=service__pb2.CreateTicketRequest.FromString,
                    response_serializer=service__pb2.Ticket.SerializeToString,
            ),
            'UpdateTicketStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTicketStatus,
                    request_deserializer=service__pb2.UpdateTicketStatusRequest.FromString,
                    response_serializer=service__pb2.Ticket.SerializeToString,
            ),
            'ListTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTickets,
                    request_deserializer=service__pb2.ListTicketsRequest.FromString,
                    response_serializer=service__pb2.ListTicketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tickets.v1.TicketsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tickets.v1.TicketsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tickets.v1.TicketsService/GetTicket',
            service__pb2.GetTicketRequest.SerializeToString,
            service__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tickets.v1.TicketsService/CreateTicket',
            service__pb2.CreateTicketRequest.SerializeToString,
            service__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTicketStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tickets.v1.TicketsService/UpdateTicketStatus',
            service__pb2.UpdateTicketStatusRequest.SerializeToString,
            service__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tickets.v1.TicketsService/ListTickets',
            service__pb2.ListTicketsRequest.SerializeToString,
            service__pb2.ListTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
