# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\ntickets.v1\"\x1e\n\x10GetTicketRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x13\x43reateTicketRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"7\n\x19UpdateTicketStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"<\n\x12ListTicketsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\"O\n\x13ListTicketsResponse\x12#\n\x07tickets\x18\x01 \x03(\x0b\x32\x12.tickets.v1.Ticket\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"p\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t2\xb5\x02\n\x0eTicketsService\x12=\n\tGetTicket\x12\x1c.tickets.v1.GetTicketRequest\x1a\x12.tickets.v1.Ticket\x12\x43\n\x0c\x43reateTicket\x12\x1f.tickets.v1.CreateTicketRequest\x1a\x12.tickets.v1.Ticket\x12O\n\x12UpdateTicketStatus\x12%.tickets.v1.UpdateTicketStatusRequest\x1a\x12.tickets.v1.Ticket\x12N\n\x0bListTickets\x12\x1e.tickets.v1.ListTicketsRequest\x1a\x1f.tickets.v1.ListTicketsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTICKETREQUEST']._serialized_start=29
  _globals['_GETTICKETREQUEST']._serialized_end=59
  _globals['_CREATETICKETREQUEST']._serialized_start=61
  _globals['_CREATETICKETREQUEST']._serialized_end=134
  _globals['_UPDATETICKETSTATUSREQUEST']._serialized_start=136
  _globals['_UPDATETICKETSTATUSREQUEST']._serialized_end=191
  _globals['_LISTTICKETSREQUEST']._serialized_start=193
  _globals['_LISTTICKETSREQUEST']._serialized_end=253
  _globals['_LISTTICKETSRESPONSE']._serialized_start=255
  _globals['_LISTTICKETSRESPONSE']._serialized_end=334
  _globals['_TICKET']._serialized_start=336
  _globals['_TICKET']._serialized_end=448
  _globals['_TICKETSSERVICE']._serialized_start=451
  _globals['_TICKETSSERVICE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
